apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud
  name: cloud
  namespace: cn202004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - image: harbor.edu.cn/cn202004/cloud:0.0.0
        imagePullPolicy: Always
        name: cloud
      imagePullSecrets:
      - name: cn202004
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud
  name: cloud
  namespace: cn202004
spec:
  ports:
  - name: cloud
    nodePort: 36000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud
  type: NodePort
