apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud
  name: cloud
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - image: pkun/cloud:1.0.0
        imagePullPolicy: IfNotPresent
        name: cloud
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud
  name: cloud
  namespace: default
spec:
  ports:
  - name: cloud
    nodePort: 32576
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud
  type: NodePort
