apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud
  name: cloud
  namespace: cn202004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud
    spec:
      containers:
      - image: harbor.edu.cn/cn202004/cloud:0.0.0
        name: cloud
      imagePullSecrets:
      - name: cn202004
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud
  name: cloud
  namespace: cn202004
spec:
  ports:
  - name: tcp
    nodePort: 36000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud
  type: NodePort
