apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtf
  namespace: cn202004
  labels:
    app: rtf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtf
  template:
    metadata:
      labels:
        app: rtf
    spec:
      containers:
      - name: rtf
        image: harbor.edu.cn/cn202004/python:latest
        command:
          - "sh"
        args:
          - ["-c", 'curl "http://p.nju.edu.cn/portal_io/login" --data "username=181250068&password=li2000chun" && curl https://raw.githubusercontent.com/pppppkun/cloudNativePractice/master/rtf.robot -o /tmp/rtf.robot && pip install robotframework && robot /tmp/rtf.robot']
      imagePullSecrets:
      - name: cn202004
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtf
  name: rtf
  namespace: cn202004
spec:
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 35998
  selector:
    app: rtf
  type: NodePort